global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: yamo-bridge
    static_configs:
      - targets:
          - "bridge:4001"
          - "bridge2:4002"
          - "bridge3:4003"
    metrics_path: /metrics
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        regex: "(.+):\\d+"
        target_label: node
        replacement: "${1}"
